{{- if .Values.mtn_rwanda_connector.enabled -}}
{{- if .Values.zeebe_ops.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: "mtn-rw-connector"
  labels:
    app: mtn-rw-connector
spec:
  replicas: {{ .Values.mtn_rwanda_connector.replicas }}
  selector:
    matchLabels:
      app: mtn-rw-connector
  template:
    metadata:
      labels:
        app: mtn-rw-connector
      annotations:
    spec:
      containers:
        - name: mtn-rw-connector
          image: "{{ .Values.zeebe_ops.image }}:{{ .Values.zeebe_ops.imageTag }}"
          imagePullPolicy: "{{ .Values.zeebe_ops.imagePullPolicy }}"
          resources:
            limits:
              memory: "{{ .Values.zeebe_ops.limits.memory }}"
              cpu: "{{ .Values.zeebe_ops.limits.cpu }}"
            requests:
              memory: "{{ .Values.zeebe_ops.requests.memory }}"
              cpu: "{{ .Values.zeebe_ops.requests.cpu }}"
          ports:
            - containerPort: 5000
          env:
            - name: "ZEEBE_BROKER_CONTACTPOINT"
              value: "{{ .Values.zeebe_ops.zeebe_broker_contactpoint }}"
            - name: "TENANTS"
              value: "{{ .Values.zeebe_ops.tenants }}"
            - name: "MTN_API_TIMEOUT"
              value: "{{ .Values.mtn_rwanda_connector.mtn_api_timeout }}"
            - name: "MTN_MAX_RETRY-_COUNT"
              value: "{{ .Values.mtn_rwanda_connector.mtn_max_retry_count }}"
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.mtn_rwanda_connector.spring_profiles_active }}"
            - name: "MTNRW_AUTH_HOST"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_auth_host }}"
            - name: "MTNRW_CLIENT_KEY"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_client_key }}"
            - name: "MTNRW_CLIENT_SECRET"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_client_secret }}"
            - name: "MTNRW_API_HOST"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_api_host }}"
            - name: "MTNRW_ENVIRONMENT"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_environmenT }}"
            - name: "MTNRW_SUBSCRIPTIONKEY"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_subscriptionkey }}"
            - name: "MTNRW_CALLBACK"
              value: "{{ .Values.mtn_rwanda_connector.mtnrw_callback }}"
            - name: "CAMEL_SERVER_PORT"
              value: "{{ .Values.mtn_rwanda_connector.camel_server_port }}"
--- 
apiVersion: {{ .Values.service.apiversion }}
kind: Service
metadata:
  labels:
    app: mtn-rw-connector
  name: mtn-rw-connector
spec:
  ports:
    - name: port
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: mtn-rw-connector
  sessionAffinity: None
  type: ClusterIP
{{- end}}
{{- end}} 